config/routes.rb
Rails.application.routes.draw do
  resources :user_standups
  resources :standups, only: [:new, :create, :index, :show]
  resources :user_teams
  get "admin/connections", to: "admin#connections"
  get "admin/setup"
  resources :teams
    resources :posts
  resources :questions
  resources :users
  resources :user_teams
  resources :home, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :sessions, only: [:new, :create, :destroy]
  get "/login", to: "sessions#new", as: :login
  get "/logout", to: "sessions#destroy", as: :logout
  # delete "/log_out", to: "sessions#destroy", as: :log_out

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "user_standups#index"
end

app/models/user_standup.rb
# == Schema Information
#
# Table name: user_standups
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  standup_id :integer          not null
#  team_id    :integer          not null
#  user_id    :integer          not null
#
# Indexes
#
#  index_user_standups_on_standup_id  (standup_id)
#  index_user_standups_on_team_id     (team_id)
#  index_user_standups_on_user_id     (user_id)
#
# Foreign Keys
#
#  standup_id  (standup_id => standups.id)
#  team_id     (team_id => teams.id)
#  user_id     (user_id => users.id)
#
class UserStandup < ApplicationRecord
  belongs_to :team
  belongs_to :user
  belongs_to :standup
  has_many :posts
  accepts_nested_attributes_for :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  helper_method :current_admin

  def current_admin
    current_user&.admin
  end

  def current_team
    current_user&.team
  end

  private

  def not_authenticated
    flash[:warning] = "You have to authenticate to access this page."
    redirect_to login_path
  end
end

app/controllers/user_standups_controller.rb
class UserStandupsController < ApplicationController
  before_action :set_user_standup, only: %i[ show edit update destroy ]

  # GET /user_standups or /user_standups.json
  def index
    # @user_standups = UserStandup.all.includes(:standup).order("standups.date desc")
    @user_standups = UserStandup.all.reverse
  end

  # GET /user_standups/1 or /user_standups/1.json
  def show
  end

  # GET /user_standups/new
  def new
    @users = User.all
    @teams = Team.all
    standup = Standup.find_or_create_by(team: current_team, date: Date.today)
    @standups = Standup.all
    posts = standup.questions.map { |question| Post.new(team: current_team, user: current_user, standup_date: standup.date, question: question) }
    @user_standup = UserStandup.new(user: current_user, team: current_team, standup: standup, posts: posts)
  end

  # GET /user_standups/1/edit
  def edit
  end

  # POST /user_standups or /user_standups.json
  def create
    team_id = user_standup_params[:team_id]
    user_id = user_standup_params[:user_id]
    create_params_hash = user_standup_params.to_h
    create_params_hash[:posts_attributes].each do |_, post|
      post[:team_id] = team_id
      post[:team] = Team.find(team_id)
      post[:user_id] = user_id
      post[:content] = "<empty>" if post[:content].blank?
    end

    @user_standup = UserStandup.new(create_params_hash)
    @users = User.all
    @teams = Team.all
    @standups = Standup.all

    respond_to do |format|
      if @user_standup.save
        format.html { redirect_to user_standup_url(@user_standup), notice: "User standup was successfully created." }
        format.json { render :show, status: :created, location: @user_standup }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_standup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_standups/1 or /user_standups/1.json
  def update
    respond_to do |format|
      if @user_standup.update(user_standup_params)
        format.html { redirect_to user_standup_url(@user_standup), notice: "User standup was successfully updated." }
        format.json { render :show, status: :ok, location: @user_standup }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_standup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_standups/1 or /user_standups/1.json
  def destroy
    @user_standup.destroy!

    respond_to do |format|
      format.html { redirect_to user_standups_url, notice: "User standup was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_standup
      @user_standup = UserStandup.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_standup_params
      params.require(:user_standup).permit(:team_id, :user_id, :standup_id, posts_attributes: [:id, :content, :team_id, :team, :user_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  # https://gist.github.com/fjahr/b3828b9f4e333e74ba1894687d65e055
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning', notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = [])
    return '' unless flash.any?

    flash.each do |msg_type, message|
      next unless !message.nil? && message.to_s.length.positive?

      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
        concat content_tag(:button, 'x', class: 'close', data: { dismiss: 'alert' })
        concat message
      end)
    end
    nil
  end

  # for outputting an objects error messages
  def errors_for(object)
    return '' unless object.errors.any?

    content_tag(:div, class: 'card border-danger') do
      concat(content_tag(:div, class: 'card-header bg-danger text-white') do
        concat "#{pluralize(object.errors.count, 'error')} prohibited this #{object.class.name.downcase} from being saved:"
      end)
      concat(content_tag(:ul, class: 'mb-0 list-group list-group-flush') do
        object.errors.full_messages.each do |msg|
          concat content_tag(:li, msg, class: 'list-group-item')
        end
      end)
    end
  end

  def is_active(this_controller)
    controller_name == this_controller.to_s ? "active" : nil        
  end
end

app/views/application/user_standups/_form.html.erb
<%= form_with(model: @user_standup, local: true) do |f| %>
  <%= errors_for(@user_standup) %>

  <div class="<%= "d-none" if @user_standup.team %>">
    <%= f.label :team %>
    <%= f.text_field :team, class: 'form-control' %>
  </div>
  <div class="<%= "d-none" if @user_standup.user %>">
    <%= f.label :user %>
    <%= f.text_field :user, class: 'form-control' %>
  </div>
  <div class="<%= "d-none" if @user_standup.standup %>">
    <%= f.label :standup %>
    <%= f.text_field :standup, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/application/user_standups/_user_post.html.erb
<div class="card" >
  <div class="card-header"><%= post.question %></div>
  <div class="card-body">
    <p class="card-text">
      <%= post.content %>
    </p>
  </div>
</div>

app/views/application/user_standups/_user_standup.html.erb
<div class="row">
  <div class="col-md-4 mb-3">
    <%= render "user_post", post: user_standup.posts.first %>
  </div>
  <div class="col-md-4 mb-3">
    <%= render "user_post", post: user_standup.posts.second %>
  </div>
  <div class="col-md-4 mb-3">
    <%= render "user_post", post: user_standup.posts.third %>
  </div>
</div>

app/views/application/user_standups/edit.html.erb
<h1>Editing User Standups</h1>


<%= render 'form', user_standup: @user_standup %>

<%= link_to 'Show', @user_standup %> |
<%= link_to 'Back', user_standups_path %>

app/views/application/user_standups/index.html.erb
<% @user_standups.each do |user_standup| %>
  <h3><%= user_standup.user.name %> - <%= user_standup.standup.date %> </h3>
  <%= render user_standup %>
  <p>
    <%= link_to "Show this entry", user_standup %>
  </p>
<% end %>

<%= render 'shared/pagination' %>
<br>
<%= link_to 'New User Standup', new_user_standup_path %>

app/views/application/user_standups/new.html.erb
<h1>New User Standups</h1>

<%= render 'form', user_standup: @user_standup %>

<%= link_to 'Back', user_standups_path %>

app/views/application/user_standups/show.html.erb
<h1><%= @user_standup.team.name %> - <%= @user_standup.user.name %> - <%= @user_standup.standup.date %> </h1>

<%= render @user_standup %>

<%= link_to 'Edit', edit_user_standup_path(@user_standup) %> |
<%= link_to 'Back', user_standups_path %>